---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age17gzsgtkqtlhs4tk52lgklz0fm7azyzydj00l4r2h6xjz7t0ata8qkygp25"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age17gzsgtkqtlhs4tk52lgklz0fm7azyzydj00l4r2h6xjz7t0ata8qkygp25"
