apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:U3ZInDjIq0A8ug53Lg11O3IdsSTUPnO+6pzK0/p7O5A=,iv:hqTFh9+DLm8dgWd+lya7ACiYNl6HPnaAxkKW3OSTqc4=,tag:w0XX/XjLQUujKYzNc+YJ8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17gzsgtkqtlhs4tk52lgklz0fm7azyzydj00l4r2h6xjz7t0ata8qkygp25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TldWS1IySVFzVnhjMG92
            ODRBOWlXcDJaT1hvKzV4bzlVSmt5MzdON0NrClQ4WjBJTHgrc0RDb2kxbFlQY3dB
            Wm5HWVA1ZnFIUFFEaHFBTXBsWUFtSmMKLS0tIE80b3R0blJyaUd5a05BMERPY2pC
            WDREWDNtZ2JnLzhZV2liY0g5WGJnS1EKIqVi4MqNt9TfihBW2YST9QhB1yksrwXq
            AqTNTiELIIzzHKpwKk7qS7uhwYzclUCETAtXNrGIFoQMthEqPWhcSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-28T06:38:54Z"
    mac: ENC[AES256_GCM,data:bfpFB31uqcR4kMJ8VZD3deddUl2ACX94hoEJxTqLlRBBhNS/TYMguTBdpJ8cbmEu/rUgU4Rt0LJGZwsb+cAmdYoUvohcgDFRRBunTuJjwmyS30wb8cITT0f7C0MTLb6w2vbN0201XhOnEvqAr/yK+Bg5sA9r2MPWDx/QktHdLgA=,iv:H+r1YueGoOsnMxereM2BJ2GOyTDILbbZ7Q1i1RAKwn0=,tag:xElXDio4hbWJomQwxDQQQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
